//
//  AppReviewTimeMonitorStyleKit.swift
//  ProjectName
//
//  Created by Alexander Kasimir on 26/10/15.
//  Copyright (c) 2015 kasimir.technology. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import Cocoa

public class AppReviewTimeMonitorStyleKit : NSObject {

    //// Drawing Methods

    public class func drawStatusBarImage(dayLabel dayLabel: String = "99") {
        //// General Declarations
        _ = unsafeBitCast(NSGraphicsContext.currentContext()!.graphicsPort, CGContext.self)

        //// Rectangle Drawing
        let rectanglePath = NSBezierPath(roundedRect: NSMakeRect(1, 5, 20, 13), xRadius: 3, yRadius: 3)
        NSColor.blackColor().setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()


        //// Text Drawing
        let textRect = NSMakeRect(3, 6, 16, 11)
        let textStyle = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        textStyle.alignment = .Center

        let textFontAttributes = [NSFontAttributeName: NSFont.labelFontOfSize(12), NSForegroundColorAttributeName: NSColor.blackColor(), NSParagraphStyleAttributeName: textStyle]

        let textTextHeight: CGFloat = NSString(string: dayLabel).boundingRectWithSize(NSMakeSize(textRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes).size.height
        let textTextRect: NSRect = NSMakeRect(textRect.minX, textRect.minY + (textRect.height - textTextHeight) / 2, textRect.width, textTextHeight)
        NSGraphicsContext.saveGraphicsState()
        NSRectClip(textRect)
        NSString(string: dayLabel).drawInRect(NSOffsetRect(textTextRect, 0, 1), withAttributes: textFontAttributes)
        NSGraphicsContext.restoreGraphicsState()
    }

    //// Generated Images

    public class func imageOfStatusBarImage(dayLabel dayLabel: String = "99") -> NSImage {
        return NSImage(size: NSMakeSize(22, 22), flipped: false) { (NSRect) -> Bool in 
                AppReviewTimeMonitorStyleKit.drawStatusBarImage(dayLabel: dayLabel)

            return true
        }
    }

}
